version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  transactions-db:
    image: mysql
    container_name: transactions-db
    environment:
      - MYSQL_DATABASE=transactions_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"

  users-db:
    image: mysql
    container_name: users-db
    environment:
      - MYSQL_DATABASE=users_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  payment-db:
      image: mysql
      container_name: payment-db
      environment:
        - MYSQL_DATABASE=payment_db
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - "3308:3306"

