spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
        - id: account-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/accounts/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
security:
  jwt:
    base64-secret-key: VWNmMnFzNGh1S2JxMVdvajc2dzhMSUJGbVlyY0paVWtQT1N1aWxxWHRqYmtwaHhJbEZpSkIxcHRqaHZhVUQ3STE1bVhXR1JLTWxQYnR4enlEb0pST3FFcUFWZWVvOWw1c0l6NWRUanRNemlobllxRXZFZ3NteWJUNkxmeDFFNXJRY0hrc21fTmc5UkZ2QzhqekdOeEZXOXR6NVNjQTlHcVlGamRHNFBsV3Jz

logging:
  level:
    root: debug