server:
  port: 8082
spring:
  application:
    name: ms-payment
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        acks: 1
        retries: 3
        retry.backoff.ms: 1000
        request.timeout.ms: 3000
        delivery.timeout.ms: 4000
    topics:
      transaction: transaction-topic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/payment_db?createIfDatabaseNotExist=true
    username: root
    password: password
    jpa:
      hibernate:
       ddl-auto: none # Liquibase will manage migrations
      properties:
        hibernate:
          format_sql: true
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
